# Generated by Django 4.2.6 on 2023-10-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atwin_backend', '0002_league_player_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='coutnry',
            new_name='country',
        ),
    ]
