# Generated by Django 4.2.6 on 2023-10-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atwin_backend', '0003_rename_coutnry_player_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='Serve',
            field=models.CharField(default='Player 1', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='Winner',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
