# Generated by Django 4.2.6 on 2023-10-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atwin_backend', '0004_match_serve_alter_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='Comments',
            field=models.JSONField(null=True),
        ),
    ]
